[workspace]
git_release_enable = false
dependencies_update = false

[changelog]
body = """
# Changelog

All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).

## [Unreleased]

"""

[[package]]
name = "geo"
git_release_enable = true

[[package]]
name = "gimme"
git_release_enable = true

[[package]]
name = "voidline"
git_release_enable = true

[[package]]
name = "costlens"
git_release_enable = true

[[package]]
name = "labstools"
git_release_enable = true
